// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC43SgV27A1UXzbu1--2c6uaO_rYCdc6qs',
    appId: '1:52088142288:web:7ac05423e9b91d3e9f61d5',
    messagingSenderId: '52088142288',
    projectId: 'tfg-control-obra',
    authDomain: 'tfg-control-obra.firebaseapp.com',
    storageBucket: 'tfg-control-obra.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpCp8cXQjI-dL-sSvyZprbcsYDwnXKYUc',
    appId: '1:52088142288:android:2f9640d45fe7e17c9f61d5',
    messagingSenderId: '52088142288',
    projectId: 'tfg-control-obra',
    storageBucket: 'tfg-control-obra.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCfLiOOtfipSJEvtrfw3Vc3UmcYLvh7cU',
    appId: '1:52088142288:ios:a504b290da12e6d39f61d5',
    messagingSenderId: '52088142288',
    projectId: 'tfg-control-obra',
    storageBucket: 'tfg-control-obra.firebasestorage.app',
    iosBundleId: 'com.example.flutterTfg1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCfLiOOtfipSJEvtrfw3Vc3UmcYLvh7cU',
    appId: '1:52088142288:ios:a504b290da12e6d39f61d5',
    messagingSenderId: '52088142288',
    projectId: 'tfg-control-obra',
    storageBucket: 'tfg-control-obra.firebasestorage.app',
    iosBundleId: 'com.example.flutterTfg1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC43SgV27A1UXzbu1--2c6uaO_rYCdc6qs',
    appId: '1:52088142288:web:d8ac8ea7aec71b969f61d5',
    messagingSenderId: '52088142288',
    projectId: 'tfg-control-obra',
    authDomain: 'tfg-control-obra.firebaseapp.com',
    storageBucket: 'tfg-control-obra.firebasestorage.app',
  );
}
